# File Handling
import csv
import os

# Database
import pandas as pd
import numpy as np

# JSON Data - Top Exchange Traded Funds (ETF) Quote Data
dd = {
    "start": 0,
    "count": 25,
    "total": 482,
    "quotes": [
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 7.73848,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1459863000000,
            "regularMarketChange": 1.8797,
            "regularMarketTime": 1584129599,
            "regularMarketPrice": 26.17,
            "regularMarketDayHigh": 25.64,
            "regularMarketDayRange": "24.6287 - 25.64",
            "regularMarketDayLow": 24.6287,
            "regularMarketVolume": 37885,
            "regularMarketPreviousClose": 24.2903,
            "bid": 0,
            "ask": 0,
            "bidSize": 8,
            "askSize": 12,
            "exchange": "BTS",
            "market": "us_market",
            "messageBoardId": "finmb_323111109",
            "fullExchangeName": "BATS",
            "shortName": "WisdomTree Emerging Markets Div",
            "longName": "WisdomTree Emerging Markets ESG Fund",
            "regularMarketOpen": 25.7,
            "averageDailyVolume3Month": 15589,
            "averageDailyVolume10Day": 15589,
            "fiftyTwoWeekLowChange": 5.497101,
            "fiftyTwoWeekLowChangePercent": 0.26590857,
            "fiftyTwoWeekRange": "20.6729 - 33.608",
            "fiftyTwoWeekHighChange": -7.4380016,
            "fiftyTwoWeekHighChangePercent": -0.2213164,
            "fiftyTwoWeekLow": 20.6729,
            "fiftyTwoWeekHigh": 33.608,
            "ytdReturn": -11.81,
            "trailingThreeMonthReturns": -6.14,
            "trailingThreeMonthNavReturns": -5.43,
            "marketState": "PREPRE",
            "fiftyDayAverage": 23.8,
            "fiftyDayAverageChange": 2.3700008,
            "fiftyDayAverageChangePercent": 0.09957987,
            "twoHundredDayAverage": 23.379335,
            "twoHundredDayAverageChange": 2.7906647,
            "twoHundredDayAverageChangePercent": 0.11936458,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "DVEM",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 7.64414,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1340026200000,
            "regularMarketChange": 2.0471,
            "regularMarketTime": 1584129515,
            "regularMarketPrice": 28.8271,
            "regularMarketDayHigh": 28.85,
            "regularMarketDayRange": "26.97 - 28.85",
            "regularMarketDayLow": 26.97,
            "regularMarketVolume": 49770,
            "regularMarketPreviousClose": 26.78,
            "bid": 0,
            "ask": 0,
            "bidSize": 13,
            "askSize": 11,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_32849134",
            "fullExchangeName": "NYSEArca",
            "shortName": "WisdomTree U.S. Total Market Fu",
            "longName": "WisdomTree U.S. ESG Fund",
            "regularMarketOpen": 28.5,
            "averageDailyVolume3Month": 15070,
            "averageDailyVolume10Day": 15070,
            "fiftyTwoWeekLowChange": 5.2700005,
            "fiftyTwoWeekLowChangePercent": 0.22371176,
            "fiftyTwoWeekRange": "23.5571 - 37.89",
            "fiftyTwoWeekHighChange": -9.062899,
            "fiftyTwoWeekHighChangePercent": -0.23918973,
            "fiftyTwoWeekLow": 23.5571,
            "fiftyTwoWeekHigh": 37.89,
            "ytdReturn": -11.07,
            "trailingThreeMonthReturns": -8.44,
            "trailingThreeMonthNavReturns": -8.42,
            "marketState": "PREPRE",
            "fiftyDayAverage": 28.2147,
            "fiftyDayAverageChange": 0.61240005,
            "fiftyDayAverageChangePercent": 0.021705,
            "twoHundredDayAverage": 26.854895,
            "twoHundredDayAverageChange": 1.9722061,
            "twoHundredDayAverageChangePercent": 0.07343935,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "EXT",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 2.7479699,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1279891800000,
            "postMarketChangePercent": 0.22924136,
            "postMarketTime": 1601414144,
            "postMarketPrice": 39.35,
            "postMarketChange": 0.09000015,
            "regularMarketChange": 1.0499992,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 39.26,
            "regularMarketDayHigh": 39.4499,
            "regularMarketDayRange": "38.73 - 39.4499",
            "regularMarketDayLow": 38.73,
            "regularMarketVolume": 454763,
            "regularMarketPreviousClose": 38.21,
            "bid": 39.3,
            "ask": 39.39,
            "bidSize": 8,
            "askSize": 8,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_109863931",
            "fullExchangeName": "NYSEArca",
            "shortName": "Global X Lithium & Battery Tech",
            "longName": "Global X Lithium & Battery Tech ETF",
            "regularMarketOpen": 38.93,
            "averageDailyVolume3Month": 385557,
            "averageDailyVolume10Day": 444133,
            "fiftyTwoWeekLowChange": 21.429998,
            "fiftyTwoWeekLowChangePercent": 1.2019068,
            "fiftyTwoWeekRange": "17.83 - 41.17",
            "fiftyTwoWeekHighChange": -1.9099998,
            "fiftyTwoWeekHighChangePercent": -0.046393003,
            "fiftyTwoWeekLow": 17.83,
            "fiftyTwoWeekHigh": 41.17,
            "ytdReturn": 44.3,
            "trailingThreeMonthReturns": 38.48,
            "trailingThreeMonthNavReturns": 39.37,
            "marketState": "PREPRE",
            "fiftyDayAverage": 38.725716,
            "fiftyDayAverageChange": 0.5342827,
            "fiftyDayAverageChangePercent": 0.013796587,
            "twoHundredDayAverage": 31.127972,
            "twoHundredDayAverageChange": 8.132027,
            "twoHundredDayAverageChangePercent": 0.26124498,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "LIT",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 1.7260432,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1577457000000,
            "postMarketChangePercent": 0.8872972,
            "postMarketTime": 1601416309,
            "postMarketPrice": 64.81,
            "postMarketChange": 0.5699997,
            "regularMarketChange": 1.0899963,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 64.24,
            "regularMarketDayHigh": 64.65,
            "regularMarketDayRange": "62.91 - 64.65",
            "regularMarketDayLow": 62.91,
            "regularMarketVolume": 1012609,
            "regularMarketPreviousClose": 63.15,
            "bid": 64.21,
            "ask": 64.3,
            "bidSize": 11,
            "askSize": 10,
            "exchange": "BTS",
            "market": "us_market",
            "messageBoardId": "finmb_268203657",
            "fullExchangeName": "BATS",
            "shortName": "ARK Genomic Revolution ETF",
            "longName": "ARK Genomic Revolution ETF",
            "regularMarketOpen": 63.24,
            "averageDailyVolume3Month": 815365,
            "averageDailyVolume10Day": 678100,
            "fiftyTwoWeekLowChange": 40.239998,
            "fiftyTwoWeekLowChangePercent": 1.6766666,
            "fiftyTwoWeekRange": "24.0 - 64.65",
            "fiftyTwoWeekHighChange": -0.41000366,
            "fiftyTwoWeekHighChangePercent": -0.006341897,
            "fiftyTwoWeekLow": 24,
            "fiftyTwoWeekHigh": 64.65,
            "ytdReturn": 84.46,
            "trailingThreeMonthReturns": 33.61,
            "trailingThreeMonthNavReturns": 33.64,
            "marketState": "PREPRE",
            "fiftyDayAverage": 60.327858,
            "fiftyDayAverageChange": 3.91214,
            "fiftyDayAverageChangePercent": 0.06484798,
            "twoHundredDayAverage": 48.536297,
            "twoHundredDayAverageChange": 15.703701,
            "twoHundredDayAverageChangePercent": 0.32354552,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "ARKG",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 2.1270418,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1288877400000,
            "regularMarketChange": 0.73999786,
            "regularMarketTime": 1601409580,
            "regularMarketPrice": 35.53,
            "regularMarketDayHigh": 35.57,
            "regularMarketDayRange": "35.02 - 35.57",
            "regularMarketDayLow": 35.02,
            "regularMarketVolume": 8459,
            "regularMarketPreviousClose": 34.79,
            "bid": 35.3,
            "ask": 40,
            "bidSize": 8,
            "askSize": 10,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_115372430",
            "fullExchangeName": "NYSEArca",
            "shortName": "Global X Gold Explorers ETF",
            "longName": "Global X Gold Explorers ETF",
            "regularMarketOpen": 35.02,
            "averageDailyVolume3Month": 30223,
            "averageDailyVolume10Day": 29450,
            "fiftyTwoWeekLowChange": 22.98,
            "fiftyTwoWeekLowChangePercent": 1.8310757,
            "fiftyTwoWeekRange": "12.55 - 40.98",
            "fiftyTwoWeekHighChange": -5.450001,
            "fiftyTwoWeekHighChangePercent": -0.13299172,
            "fiftyTwoWeekLow": 12.55,
            "fiftyTwoWeekHigh": 40.98,
            "ytdReturn": 42.25,
            "trailingThreeMonthReturns": 27.72,
            "trailingThreeMonthNavReturns": 28.2,
            "marketState": "PREPRE",
            "fiftyDayAverage": 36.972286,
            "fiftyDayAverageChange": -1.4422874,
            "fiftyDayAverageChangePercent": -0.039009962,
            "twoHundredDayAverage": 30.606522,
            "twoHundredDayAverageChange": 4.923477,
            "twoHundredDayAverageChangePercent": 0.16086367,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "GOEX",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "true",
            "currency": "USD",
            "regularMarketChangePercent": 1.6739025,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1328193000000,
            "postMarketChangePercent": 0.7326059,
            "postMarketTime": 1601418209,
            "postMarketPrice": 33,
            "postMarketChange": 0.24000168,
            "regularMarketChange": 0.5400009,
            "regularMarketTime": 1601409602,
            "regularMarketPrice": 32.8,
            "regularMarketDayHigh": 32.91,
            "regularMarketDayRange": "32.3859 - 32.91",
            "regularMarketDayLow": 32.3859,
            "regularMarketVolume": 92007,
            "regularMarketPreviousClose": 32.26,
            "bid": 31.4,
            "ask": 34.55,
            "bidSize": 12,
            "askSize": 8,
            "exchange": "NMS",
            "market": "us_market",
            "messageBoardId": "finmb_160291964",
            "fullExchangeName": "NasdaqGS",
            "shortName": "iShares MSCI Global Gold Miners",
            "longName": "iShares MSCI Global Gold Miners ETF",
            "regularMarketOpen": 32.42,
            "averageDailyVolume3Month": 239326,
            "averageDailyVolume10Day": 195333,
            "fiftyTwoWeekLowChange": 18.789999,
            "fiftyTwoWeekLowChangePercent": 1.3411847,
            "fiftyTwoWeekRange": "14.01 - 37.96",
            "fiftyTwoWeekHighChange": -5.16,
            "fiftyTwoWeekHighChangePercent": -0.13593256,
            "fiftyTwoWeekLow": 14.01,
            "fiftyTwoWeekHigh": 37.96,
            "dividendDate": 1514246400,
            "ytdReturn": 24.27,
            "trailingThreeMonthReturns": 57.62,
            "trailingThreeMonthNavReturns": 54.06,
            "marketState": "PREPRE",
            "sharesOutstanding": 11500000,
            "fiftyDayAverage": 34.126,
            "fiftyDayAverageChange": -1.3260002,
            "fiftyDayAverageChangePercent": -0.03885601,
            "twoHundredDayAverage": 29.440073,
            "twoHundredDayAverageChange": 3.3599262,
            "twoHundredDayAverageChangePercent": 0.11412764,
            "marketCap": 377200000,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "RING",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 1.3747289,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1351171800000,
            "regularMarketChange": 1.9929047,
            "regularMarketTime": 1601319477,
            "regularMarketPrice": 146.96,
            "regularMarketDayHigh": 146.96,
            "regularMarketDayRange": "146.94 - 146.96",
            "regularMarketDayLow": 146.94,
            "regularMarketVolume": 130,
            "regularMarketPreviousClose": 144.967,
            "bid": 146.92,
            "ask": 147,
            "bidSize": 10,
            "askSize": 10,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_216338006",
            "fullExchangeName": "NYSEArca",
            "shortName": "SPDR S&P 1500 Momentum Tilt ETF",
            "longName": "SPDR S&P 1500 Momentum Tilt ETF",
            "regularMarketOpen": 146.7,
            "averageDailyVolume3Month": 1606,
            "averageDailyVolume10Day": 1266,
            "fiftyTwoWeekLowChange": 52.280006,
            "fiftyTwoWeekLowChangePercent": 0.5521758,
            "fiftyTwoWeekRange": "94.68 - 159.29",
            "fiftyTwoWeekHighChange": -12.329987,
            "fiftyTwoWeekHighChangePercent": -0.07740591,
            "fiftyTwoWeekLow": 94.68,
            "fiftyTwoWeekHigh": 159.29,
            "ytdReturn": -1.76,
            "trailingThreeMonthReturns": 20.68,
            "trailingThreeMonthNavReturns": 20.53,
            "marketState": "PREPRE",
            "fiftyDayAverage": 148.76457,
            "fiftyDayAverageChange": -1.8045654,
            "fiftyDayAverageChangePercent": -0.012130344,
            "twoHundredDayAverage": 133.02072,
            "twoHundredDayAverageChange": 13.939285,
            "twoHundredDayAverageChangePercent": 0.10479033,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "MMTM",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 1.2682632,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1044628200000,
            "regularMarketChange": 0.45999908,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 36.73,
            "regularMarketDayHigh": 36.99,
            "regularMarketDayRange": "36.42 - 36.99",
            "regularMarketDayLow": 36.42,
            "regularMarketVolume": 315163,
            "regularMarketPreviousClose": 36.27,
            "bid": 33.78,
            "ask": 39.99,
            "bidSize": 8,
            "askSize": 8,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_6457002",
            "fullExchangeName": "NYSEArca",
            "shortName": "iShares MSCI South Africa Index",
            "longName": "iShares MSCI South Africa ETF",
            "financialCurrency": "USD",
            "regularMarketOpen": 36.42,
            "averageDailyVolume3Month": 441179,
            "averageDailyVolume10Day": 512583,
            "fiftyTwoWeekLowChange": 12.609999,
            "fiftyTwoWeekLowChangePercent": 0.5228026,
            "fiftyTwoWeekRange": "24.12 - 52.37",
            "fiftyTwoWeekHighChange": -15.639999,
            "fiftyTwoWeekHighChangePercent": -0.29864424,
            "fiftyTwoWeekLow": 24.12,
            "fiftyTwoWeekHigh": 52.37,
            "ytdReturn": -26.6,
            "trailingThreeMonthReturns": 26.45,
            "trailingThreeMonthNavReturns": 25.9,
            "marketState": "PREPRE",
            "sharesOutstanding": 7900000,
            "fiftyDayAverage": 37.456284,
            "fiftyDayAverageChange": -0.726284,
            "fiftyDayAverageChangePercent": -0.019390179,
            "twoHundredDayAverage": 34.665436,
            "twoHundredDayAverageChange": 2.0645638,
            "twoHundredDayAverageChangePercent": 0.059556838,
            "marketCap": 290167008,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "EZA",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 1.2907134,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1250688600000,
            "regularMarketChange": 0.31499863,
            "regularMarketTime": 1601409560,
            "regularMarketPrice": 24.72,
            "regularMarketDayHigh": 24.86,
            "regularMarketDayRange": "24.6035 - 24.86",
            "regularMarketDayLow": 24.6035,
            "regularMarketVolume": 6379,
            "regularMarketPreviousClose": 24.405,
            "bid": 24.62,
            "ask": 24.86,
            "bidSize": 13,
            "askSize": 9,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_62123752",
            "fullExchangeName": "NYSEArca",
            "shortName": "Global X FTSE Nordic Region ETF",
            "longName": "Global X FTSE Nordic Region ETF",
            "regularMarketOpen": 24.585,
            "averageDailyVolume3Month": 5423,
            "averageDailyVolume10Day": 7833,
            "fiftyTwoWeekLowChange": 9.5199995,
            "fiftyTwoWeekLowChangePercent": 0.6263158,
            "fiftyTwoWeekRange": "15.2 - 25.17",
            "fiftyTwoWeekHighChange": -0.45000076,
            "fiftyTwoWeekHighChangePercent": -0.017878456,
            "fiftyTwoWeekLow": 15.2,
            "fiftyTwoWeekHigh": 25.17,
            "ytdReturn": 14.06,
            "trailingThreeMonthReturns": 20.64,
            "trailingThreeMonthNavReturns": 18.54,
            "marketState": "PREPRE",
            "fiftyDayAverage": 24.551144,
            "fiftyDayAverageChange": 0.16885567,
            "fiftyDayAverageChangePercent": 0.006877711,
            "twoHundredDayAverage": 21.498985,
            "twoHundredDayAverageChange": 3.221014,
            "twoHundredDayAverageChangePercent": 0.14982168,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "GXF",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 1.1447835,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1414762200000,
            "postMarketChangePercent": -0.18324693,
            "postMarketTime": 1601420822,
            "postMarketPrice": 92.6,
            "postMarketChange": -0.16999817,
            "regularMarketChange": 1.0499954,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 92.77,
            "regularMarketDayHigh": 93.38,
            "regularMarketDayRange": "91.74 - 93.38",
            "regularMarketDayLow": 91.74,
            "regularMarketVolume": 1524473,
            "regularMarketPreviousClose": 91.72,
            "bid": 92.78,
            "ask": 92.94,
            "bidSize": 12,
            "askSize": 10,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_268203659",
            "fullExchangeName": "NYSEArca",
            "shortName": "ARK Innovation ETF",
            "longName": "ARK Innovation ETF",
            "regularMarketOpen": 91.76,
            "averageDailyVolume3Month": 2140975,
            "averageDailyVolume10Day": 2066366,
            "fiftyTwoWeekLowChange": 59.769997,
            "fiftyTwoWeekLowChangePercent": 1.8112121,
            "fiftyTwoWeekRange": "33.0 - 98.9",
            "fiftyTwoWeekHighChange": -6.130005,
            "fiftyTwoWeekHighChangePercent": -0.06198185,
            "fiftyTwoWeekLow": 33,
            "fiftyTwoWeekHigh": 98.9,
            "ytdReturn": 90.02,
            "trailingThreeMonthReturns": 51.75,
            "trailingThreeMonthNavReturns": 51.37,
            "marketState": "PREPRE",
            "fiftyDayAverage": 89.026855,
            "fiftyDayAverageChange": 3.7431412,
            "fiftyDayAverageChangePercent": 0.04204508,
            "twoHundredDayAverage": 68.905075,
            "twoHundredDayAverageChange": 23.864922,
            "twoHundredDayAverageChangePercent": 0.34634492,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "ARKK",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": -0.5842986,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1449153000000,
            "regularMarketChange": -0.4543991,
            "regularMarketTime": 1601408770,
            "regularMarketPrice": 77.3139,
            "regularMarketDayHigh": 77.85,
            "regularMarketDayRange": "77.08 - 77.85",
            "regularMarketDayLow": 77.08,
            "regularMarketVolume": 1123,
            "regularMarketPreviousClose": 77.7683,
            "bid": 77.43,
            "ask": 77.43,
            "bidSize": 8,
            "askSize": 11,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_315147049",
            "fullExchangeName": "NYSEArca",
            "shortName": "SPDR Russell 1000 Low Volatilit",
            "longName": "SPDR Russell 1000 Low Volatility Focus ETF",
            "regularMarketOpen": 77.85,
            "averageDailyVolume3Month": 23432,
            "averageDailyVolume10Day": 4150,
            "fiftyTwoWeekLowChange": 25.548904,
            "fiftyTwoWeekLowChangePercent": 0.49355558,
            "fiftyTwoWeekRange": "51.765 - 88.1",
            "fiftyTwoWeekHighChange": -10.786095,
            "fiftyTwoWeekHighChangePercent": -0.12243013,
            "fiftyTwoWeekLow": 51.765,
            "fiftyTwoWeekHigh": 88.1,
            "ytdReturn": -13.76,
            "trailingThreeMonthReturns": 18.78,
            "trailingThreeMonthNavReturns": 18.87,
            "marketState": "PREPRE",
            "fiftyDayAverage": 78.8982,
            "fiftyDayAverageChange": -1.5842972,
            "fiftyDayAverageChangePercent": -0.02008027,
            "twoHundredDayAverage": 72.43847,
            "twoHundredDayAverageChange": 4.875435,
            "twoHundredDayAverageChangePercent": 0.0673045,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "ONEV",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.95063907,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1119533400000,
            "regularMarketChange": 0.7299957,
            "regularMarketTime": 1601409580,
            "regularMarketPrice": 77.52,
            "regularMarketDayHigh": 77.89,
            "regularMarketDayRange": "77.08 - 77.89",
            "regularMarketDayLow": 77.08,
            "regularMarketVolume": 21697,
            "regularMarketPreviousClose": 76.79,
            "bid": 77.46,
            "ask": 77.98,
            "bidSize": 9,
            "askSize": 13,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_22938325",
            "fullExchangeName": "NYSEArca",
            "shortName": "Invesco Dynamic Semiconductors ",
            "longName": "Invesco Dynamic Semiconductors ETF",
            "financialCurrency": "USD",
            "regularMarketOpen": 76.57,
            "averageDailyVolume3Month": 28310,
            "averageDailyVolume10Day": 14383,
            "fiftyTwoWeekLowChange": 32.839996,
            "fiftyTwoWeekLowChangePercent": 0.73500437,
            "fiftyTwoWeekRange": "44.68 - 84.54",
            "fiftyTwoWeekHighChange": -7.0200043,
            "fiftyTwoWeekHighChangePercent": -0.08303767,
            "fiftyTwoWeekLow": 44.68,
            "fiftyTwoWeekHigh": 84.54,
            "ytdReturn": 20.24,
            "trailingThreeMonthReturns": 17.04,
            "trailingThreeMonthNavReturns": 17.08,
            "marketState": "PREPRE",
            "sharesOutstanding": 3200000,
            "fiftyDayAverage": 78.109146,
            "fiftyDayAverageChange": -0.5891495,
            "fiftyDayAverageChangePercent": -0.0075426437,
            "twoHundredDayAverage": 69.84101,
            "twoHundredDayAverageChange": 7.6789856,
            "twoHundredDayAverageChangePercent": 0.10994952,
            "marketCap": 248063984,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "PSI",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Nasdaq Real Time Price",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.94760346,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1106922600000,
            "postMarketChangePercent": 0,
            "postMarketTime": 1601423979,
            "postMarketPrice": 18.11,
            "postMarketChange": 0,
            "regularMarketChange": 0.17000008,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 18.11,
            "regularMarketDayHigh": 18.1167,
            "regularMarketDayRange": "17.985 - 18.1167",
            "regularMarketDayLow": 17.985,
            "regularMarketVolume": 17127865,
            "regularMarketPreviousClose": 17.94,
            "bid": 18.11,
            "ask": 18.11,
            "bidSize": 3061,
            "askSize": 3218,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_8956538",
            "fullExchangeName": "NYSEArca",
            "shortName": "ishares Gold Trust",
            "longName": "iShares Gold Trust",
            "financialCurrency": "USD",
            "regularMarketOpen": 18,
            "averageDailyVolume3Month": 27227428,
            "averageDailyVolume10Day": 25090683,
            "fiftyTwoWeekLowChange": 4.3100004,
            "fiftyTwoWeekLowChangePercent": 0.31231886,
            "fiftyTwoWeekRange": "13.8 - 19.76",
            "fiftyTwoWeekHighChange": -1.6499996,
            "fiftyTwoWeekHighChangePercent": -0.083502,
            "fiftyTwoWeekLow": 13.8,
            "fiftyTwoWeekHigh": 19.76,
            "ytdReturn": 15.97,
            "trailingThreeMonthReturns": 12.74,
            "trailingThreeMonthNavReturns": 9.82,
            "marketState": "PREPRE",
            "sharesOutstanding": 970150016,
            "fiftyDayAverage": 18.492285,
            "fiftyDayAverageChange": -0.38228416,
            "fiftyDayAverageChangePercent": -0.02067263,
            "twoHundredDayAverage": 17.087173,
            "twoHundredDayAverageChange": 1.0228271,
            "twoHundredDayAverageChangePercent": 0.059859354,
            "marketCap": 17569417216,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "IAU",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.917046,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1211463000000,
            "regularMarketChange": 0.439999,
            "regularMarketTime": 1577826000,
            "regularMarketPrice": 48.42,
            "regularMarketDayHigh": 48.0607,
            "regularMarketDayRange": "47.9117 - 48.0607",
            "regularMarketDayLow": 47.9117,
            "regularMarketVolume": 2375,
            "regularMarketPreviousClose": 47.98,
            "bid": 0,
            "ask": 0,
            "bidSize": 8,
            "askSize": 8,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_44679015",
            "fullExchangeName": "NYSEArca",
            "shortName": "Cohen & Steers Global Realty Ma",
            "longName": "Cohen & Steers Global Realty Majors ETF",
            "regularMarketOpen": 48.2,
            "averageDailyVolume3Month": 2902,
            "averageDailyVolume10Day": 2902,
            "fiftyTwoWeekLowChange": 1.699997,
            "fiftyTwoWeekLowChangePercent": 0.03638692,
            "fiftyTwoWeekRange": "46.72 - 49.86",
            "fiftyTwoWeekHighChange": -1.4400024,
            "fiftyTwoWeekHighChangePercent": -0.028880915,
            "fiftyTwoWeekLow": 46.72,
            "fiftyTwoWeekHigh": 49.86,
            "marketState": "PREPRE",
            "fiftyDayAverage": 47.615,
            "fiftyDayAverageChange": 0.8049965,
            "fiftyDayAverageChangePercent": 0.016906362,
            "twoHundredDayAverage": 47.615,
            "twoHundredDayAverageChange": 0.8049965,
            "twoHundredDayAverageChangePercent": 0.016906362,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "GRI",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.866091,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1452177000000,
            "regularMarketChange": 0.220301,
            "regularMarketTime": 1590605722,
            "regularMarketPrice": 25.6565,
            "regularMarketDayHigh": 24.83,
            "regularMarketDayRange": "24.79 - 24.83",
            "regularMarketDayLow": 24.79,
            "regularMarketVolume": 0,
            "regularMarketPreviousClose": 24.9093,
            "bid": 24.68,
            "ask": 31.5,
            "bidSize": 10,
            "askSize": 10,
            "exchange": "BTS",
            "market": "us_market",
            "messageBoardId": "finmb_318392499",
            "fullExchangeName": "BATS",
            "shortName": "WisdomTree Europe Multifactor F",
            "longName": "WisdomTree Europe Multifactor Fund",
            "regularMarketOpen": 25.62,
            "averageDailyVolume3Month": 0,
            "averageDailyVolume10Day": 0,
            "fiftyTwoWeekLowChange": 5.386801,
            "fiftyTwoWeekLowChangePercent": 0.26575634,
            "fiftyTwoWeekRange": "20.2697 - 31.5154",
            "fiftyTwoWeekHighChange": -5.8589,
            "fiftyTwoWeekHighChangePercent": -0.18590593,
            "fiftyTwoWeekLow": 20.2697,
            "fiftyTwoWeekHigh": 31.5154,
            "ytdReturn": -13.58,
            "trailingThreeMonthReturns": -8.6,
            "trailingThreeMonthNavReturns": -6.67,
            "marketState": "PREPRE",
            "fiftyDayAverage": 25.6565,
            "fiftyDayAverageChange": 0,
            "fiftyDayAverageChangePercent": 0,
            "twoHundredDayAverage": 24.069914,
            "twoHundredDayAverageChange": 1.586586,
            "twoHundredDayAverageChangePercent": 0.06591573,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "EUMF",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.9027963,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1258468200000,
            "regularMarketChange": 0.29999924,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 33.53,
            "regularMarketDayHigh": 33.62,
            "regularMarketDayRange": "33.25 - 33.62",
            "regularMarketDayLow": 33.25,
            "regularMarketVolume": 82944,
            "regularMarketPreviousClose": 33.23,
            "bid": 32,
            "ask": 0,
            "bidSize": 10,
            "askSize": 10,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_79688139",
            "fullExchangeName": "NYSEArca",
            "shortName": "IQ Merger Arbitrage ETF",
            "longName": "IQ Merger Arbitrage ETF",
            "regularMarketOpen": 33.25,
            "averageDailyVolume3Month": 94848,
            "averageDailyVolume10Day": 92750,
            "fiftyTwoWeekLowChange": 7.3199997,
            "fiftyTwoWeekLowChangePercent": 0.27928272,
            "fiftyTwoWeekRange": "26.21 - 33.62",
            "fiftyTwoWeekHighChange": -0.09000015,
            "fiftyTwoWeekHighChangePercent": -0.0026769827,
            "fiftyTwoWeekLow": 26.21,
            "fiftyTwoWeekHigh": 33.62,
            "ytdReturn": -4.97,
            "trailingThreeMonthReturns": 4.61,
            "trailingThreeMonthNavReturns": 3.99,
            "marketState": "PREPRE",
            "fiftyDayAverage": 32.363144,
            "fiftyDayAverageChange": 1.1668549,
            "fiftyDayAverageChangePercent": 0.036055055,
            "twoHundredDayAverage": 31.479202,
            "twoHundredDayAverageChange": 2.0507965,
            "twoHundredDayAverageChangePercent": 0.06514767,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "MNA",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.73674786,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 827159400000,
            "regularMarketChange": 0.25999832,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 35.55,
            "regularMarketDayHigh": 35.67,
            "regularMarketDayRange": "35.36 - 35.67",
            "regularMarketDayLow": 35.36,
            "regularMarketVolume": 588048,
            "regularMarketPreviousClose": 35.29,
            "bid": 35.57,
            "ask": 36.75,
            "bidSize": 10,
            "askSize": 11,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_6456851",
            "fullExchangeName": "NYSEArca",
            "shortName": "iShares Inc iShares MSCI Sweden",
            "longName": "iShares MSCI Sweden ETF",
            "financialCurrency": "USD",
            "regularMarketOpen": 35.5,
            "averageDailyVolume3Month": 231201,
            "averageDailyVolume10Day": 538200,
            "fiftyTwoWeekLowChange": 14.17,
            "fiftyTwoWeekLowChangePercent": 0.66276896,
            "fiftyTwoWeekRange": "21.38 - 36.4",
            "fiftyTwoWeekHighChange": -0.8500023,
            "fiftyTwoWeekHighChangePercent": -0.02335171,
            "fiftyTwoWeekLow": 21.38,
            "fiftyTwoWeekHigh": 36.4,
            "ytdReturn": -5.53,
            "trailingThreeMonthReturns": 21.8,
            "trailingThreeMonthNavReturns": 20.35,
            "marketState": "PREPRE",
            "sharesOutstanding": 7650000,
            "fiftyDayAverage": 35.439144,
            "fiftyDayAverageChange": 0.1108551,
            "fiftyDayAverageChangePercent": 0.0031280413,
            "twoHundredDayAverage": 30.804638,
            "twoHundredDayAverageChange": 4.7453613,
            "twoHundredDayAverageChangePercent": 0.15404698,
            "marketCap": 271957504,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "EWD",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "true",
            "currency": "USD",
            "regularMarketChangePercent": 0.802216,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1216128600000,
            "regularMarketChange": 0.129999,
            "regularMarketTime": 1590609596,
            "regularMarketPrice": 16.335,
            "regularMarketDayHigh": 16.4962,
            "regularMarketDayRange": "16.16 - 16.4962",
            "regularMarketDayLow": 16.16,
            "regularMarketVolume": 3032,
            "regularMarketPreviousClose": 16.205,
            "bid": 0,
            "ask": 0,
            "bidSize": 9,
            "askSize": 9,
            "exchange": "NMS",
            "market": "us_market",
            "messageBoardId": "finmb_46774454",
            "fullExchangeName": "NasdaqGS",
            "shortName": "WisdomTree Middle East Dividend",
            "longName": "WisdomTree Middle East Dividend Fund",
            "regularMarketOpen": 16.36,
            "averageDailyVolume3Month": 0,
            "averageDailyVolume10Day": 0,
            "fiftyTwoWeekLowChange": 3.494999,
            "fiftyTwoWeekLowChangePercent": 0.27219617,
            "fiftyTwoWeekRange": "12.84 - 20.735",
            "fiftyTwoWeekHighChange": -4.4000015,
            "fiftyTwoWeekHighChangePercent": -0.21220165,
            "fiftyTwoWeekLow": 12.84,
            "fiftyTwoWeekHigh": 20.735,
            "dividendDate": 1490918400,
            "ytdReturn": -18.08,
            "trailingThreeMonthReturns": -8.56,
            "trailingThreeMonthNavReturns": -11.64,
            "marketState": "PREPRE",
            "fiftyDayAverage": 16.335,
            "fiftyDayAverageChange": 0,
            "fiftyDayAverageChangePercent": 0,
            "twoHundredDayAverage": 15.647104,
            "twoHundredDayAverageChange": 0.6878948,
            "twoHundredDayAverageChangePercent": 0.043963075,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "GULF",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.718866,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1418826600000,
            "regularMarketChange": 0.27799988,
            "regularMarketTime": 1601409584,
            "regularMarketPrice": 38.95,
            "regularMarketDayHigh": 39.0632,
            "regularMarketDayRange": "38.41 - 39.0632",
            "regularMarketDayLow": 38.41,
            "regularMarketVolume": 7915,
            "regularMarketPreviousClose": 38.672,
            "bid": 35.07,
            "ask": 41.99,
            "bidSize": 8,
            "askSize": 8,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_274653436",
            "fullExchangeName": "NYSEArca",
            "shortName": "Virtus LifeSci Biotech Clinical",
            "longName": "Virtus LifeSci Biotech Clinical Trials ETF",
            "regularMarketOpen": 38.57,
            "averageDailyVolume3Month": 25368,
            "averageDailyVolume10Day": 18283,
            "fiftyTwoWeekLowChange": 16.03,
            "fiftyTwoWeekLowChangePercent": 0.6993892,
            "fiftyTwoWeekRange": "22.92 - 45.7",
            "fiftyTwoWeekHighChange": -6.75,
            "fiftyTwoWeekHighChangePercent": -0.14770241,
            "fiftyTwoWeekLow": 22.92,
            "fiftyTwoWeekHigh": 45.7,
            "dividendDate": 1514332800,
            "ytdReturn": 13.59,
            "trailingThreeMonthReturns": 47.41,
            "trailingThreeMonthNavReturns": 46.92,
            "marketState": "PREPRE",
            "fiftyDayAverage": 39.986515,
            "fiftyDayAverageChange": -1.0365143,
            "fiftyDayAverageChangePercent": -0.025921596,
            "twoHundredDayAverage": 38.36916,
            "twoHundredDayAverageChange": 0.58084106,
            "twoHundredDayAverageChangePercent": 0.0151382275,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "BBC",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.7612499,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1432819800000,
            "regularMarketChange": 0.11000061,
            "regularMarketTime": 1601409601,
            "regularMarketPrice": 14.56,
            "regularMarketDayHigh": 14.5758,
            "regularMarketDayRange": "14.425 - 14.5758",
            "regularMarketDayLow": 14.425,
            "regularMarketVolume": 11140,
            "regularMarketPreviousClose": 14.45,
            "bid": 13,
            "ask": 14.56,
            "bidSize": 10,
            "askSize": 9,
            "exchange": "NGM",
            "market": "us_market",
            "messageBoardId": "finmb_311031290",
            "fullExchangeName": "NasdaqGM",
            "shortName": "Global X YieldCo & Renewable En",
            "longName": "Global X YieldCo & Renewable Energy Income ETF",
            "regularMarketOpen": 14.47,
            "averageDailyVolume3Month": 17157,
            "averageDailyVolume10Day": 13583,
            "fiftyTwoWeekLowChange": 4.54,
            "fiftyTwoWeekLowChangePercent": 0.4530938,
            "fiftyTwoWeekRange": "10.02 - 16.259",
            "fiftyTwoWeekHighChange": -1.6990004,
            "fiftyTwoWeekHighChangePercent": -0.10449599,
            "fiftyTwoWeekLow": 10.02,
            "fiftyTwoWeekHigh": 16.259,
            "dividendDate": 1494892800,
            "ytdReturn": 0.8,
            "trailingThreeMonthReturns": 9.26,
            "trailingThreeMonthNavReturns": 8.02,
            "marketState": "PREPRE",
            "fiftyDayAverage": 14.651086,
            "fiftyDayAverageChange": -0.091085434,
            "fiftyDayAverageChangePercent": -0.006216975,
            "twoHundredDayAverage": 13.731435,
            "twoHundredDayAverageChange": 0.8285656,
            "twoHundredDayAverageChangePercent": 0.06034079,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "YLCO",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.7342125,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1420036200000,
            "regularMarketChange": 0.29999924,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 41.16,
            "regularMarketDayHigh": 41.313,
            "regularMarketDayRange": "40.69 - 41.313",
            "regularMarketDayLow": 40.69,
            "regularMarketVolume": 9600,
            "regularMarketPreviousClose": 40.86,
            "bid": 38,
            "ask": 41.23,
            "bidSize": 11,
            "askSize": 9,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_275139748",
            "fullExchangeName": "NYSEArca",
            "shortName": "ALPS Medical Breakthroughs ETF",
            "longName": "ALPS Medical Breakthroughs ETF",
            "regularMarketOpen": 40.69,
            "averageDailyVolume3Month": 22965,
            "averageDailyVolume10Day": 13333,
            "fiftyTwoWeekLowChange": 16.06,
            "fiftyTwoWeekLowChangePercent": 0.6398406,
            "fiftyTwoWeekRange": "25.1 - 45.02",
            "fiftyTwoWeekHighChange": -3.8600006,
            "fiftyTwoWeekHighChangePercent": -0.08573969,
            "fiftyTwoWeekLow": 25.1,
            "fiftyTwoWeekHigh": 45.02,
            "ytdReturn": -0.31,
            "trailingThreeMonthReturns": 31.96,
            "trailingThreeMonthNavReturns": 32.31,
            "marketState": "PREPRE",
            "fiftyDayAverage": 40.744286,
            "fiftyDayAverageChange": 0.41571426,
            "fiftyDayAverageChangePercent": 0.010203008,
            "twoHundredDayAverage": 39.349884,
            "twoHundredDayAverageChange": 1.8101158,
            "twoHundredDayAverageChangePercent": 0.046000537,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "SBIO",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.5865077,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1382448600000,
            "postMarketChangePercent": -0.029988509,
            "postMarketTime": 1601411804,
            "postMarketPrice": 48.0056,
            "postMarketChange": -0.014400482,
            "regularMarketChange": 0.27999878,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 48.02,
            "regularMarketDayHigh": 48.29,
            "regularMarketDayRange": "47.815 - 48.29",
            "regularMarketDayLow": 47.815,
            "regularMarketVolume": 89660,
            "regularMarketPreviousClose": 47.74,
            "bid": 46.05,
            "ask": 48.98,
            "bidSize": 8,
            "askSize": 14,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_246379345",
            "fullExchangeName": "NYSEArca",
            "shortName": "Exchange Traded Concepts Trust ",
            "longName": "Robo Global Robotics and Automation Index ETF",
            "regularMarketOpen": 47.9,
            "averageDailyVolume3Month": 135128,
            "averageDailyVolume10Day": 151250,
            "fiftyTwoWeekLowChange": 19.75,
            "fiftyTwoWeekLowChangePercent": 0.69862044,
            "fiftyTwoWeekRange": "28.27 - 49.71",
            "fiftyTwoWeekHighChange": -1.6899986,
            "fiftyTwoWeekHighChangePercent": -0.033997156,
            "fiftyTwoWeekLow": 28.27,
            "fiftyTwoWeekHigh": 49.71,
            "dividendDate": 1514505600,
            "ytdReturn": 3.08,
            "trailingThreeMonthReturns": 29.47,
            "trailingThreeMonthNavReturns": 28.8,
            "marketState": "PREPRE",
            "bookValue": 0.303,
            "fiftyDayAverage": 47.683144,
            "fiftyDayAverageChange": 0.33685684,
            "fiftyDayAverageChangePercent": 0.007064485,
            "twoHundredDayAverage": 42.121666,
            "twoHundredDayAverageChange": 5.8983345,
            "twoHundredDayAverageChangePercent": 0.14003089,
            "marketCap": 930819712,
            "priceToBook": 158.48184,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "ROBO",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.73709416,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1109860200000,
            "regularMarketChange": 0.47999573,
            "regularMarketTime": 1601409600,
            "regularMarketPrice": 65.6,
            "regularMarketDayHigh": 66.0468,
            "regularMarketDayRange": "65.26 - 66.0468",
            "regularMarketDayLow": 65.26,
            "regularMarketVolume": 89272,
            "regularMarketPreviousClose": 65.12,
            "bid": 65.64,
            "ask": 65.61,
            "bidSize": 10,
            "askSize": 9,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_22893057",
            "fullExchangeName": "NYSEArca",
            "shortName": "Invesco S&P MidCap Momentum ETF",
            "longName": "Invesco S&P MidCap Momentum ETF",
            "financialCurrency": "USD",
            "regularMarketOpen": 65.31,
            "averageDailyVolume3Month": 76217,
            "averageDailyVolume10Day": 93816,
            "fiftyTwoWeekLowChange": 26.239998,
            "fiftyTwoWeekLowChangePercent": 0.6666666,
            "fiftyTwoWeekRange": "39.36 - 68.01",
            "fiftyTwoWeekHighChange": -2.4100037,
            "fiftyTwoWeekHighChangePercent": -0.03543602,
            "fiftyTwoWeekLow": 39.36,
            "fiftyTwoWeekHigh": 68.01,
            "ytdReturn": 9.79,
            "trailingThreeMonthReturns": 12.05,
            "trailingThreeMonthNavReturns": 12.04,
            "marketState": "PREPRE",
            "fiftyDayAverage": 65.26143,
            "fiftyDayAverageChange": 0.33856964,
            "fiftyDayAverageChangePercent": 0.005187898,
            "twoHundredDayAverage": 58.511375,
            "twoHundredDayAverageChange": 7.088623,
            "twoHundredDayAverageChangePercent": 0.12114949,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "XMMO",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "true",
            "currency": "USD",
            "regularMarketChangePercent": 0.66223603,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1270647000000,
            "regularMarketChange": 0.8609009,
            "regularMarketTime": 1601409602,
            "regularMarketPrice": 130.86,
            "regularMarketDayHigh": 131.2118,
            "regularMarketDayRange": "129.61 - 131.2118",
            "regularMarketDayLow": 129.61,
            "regularMarketVolume": 4177,
            "regularMarketPreviousClose": 129.9991,
            "bid": 130.38,
            "ask": 131.01,
            "bidSize": 9,
            "askSize": 8,
            "exchange": "NMS",
            "market": "us_market",
            "messageBoardId": "finmb_100588930",
            "fullExchangeName": "NasdaqGS",
            "shortName": "Invesco S&P SmallCap Health Car",
            "longName": "Invesco S&P SmallCap Health Care ETF",
            "regularMarketOpen": 129.29,
            "averageDailyVolume3Month": 15090,
            "averageDailyVolume10Day": 13616,
            "fiftyTwoWeekLowChange": 47.32,
            "fiftyTwoWeekLowChangePercent": 0.5664352,
            "fiftyTwoWeekRange": "83.54 - 138.32",
            "fiftyTwoWeekHighChange": -7.4600067,
            "fiftyTwoWeekHighChangePercent": -0.053932954,
            "fiftyTwoWeekLow": 83.54,
            "fiftyTwoWeekHigh": 138.32,
            "dividendDate": 1483056000,
            "ytdReturn": 2.6,
            "trailingThreeMonthReturns": 10.72,
            "trailingThreeMonthNavReturns": 10.37,
            "marketState": "PREPRE",
            "fiftyDayAverage": 130.25285,
            "fiftyDayAverageChange": 0.6071472,
            "fiftyDayAverageChangePercent": 0.004661297,
            "twoHundredDayAverage": 119.093185,
            "twoHundredDayAverageChange": 11.766815,
            "twoHundredDayAverageChangePercent": 0.09880343,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "PSCH",
        },
        {
            "language": "en-US",
            "region": "US",
            "quoteType": "ETF",
            "quoteSourceName": "Delayed Quote",
            "triggerable": "false",
            "currency": "USD",
            "regularMarketChangePercent": 0.6588551,
            "priceHint": 2,
            "firstTradeDateMilliseconds": 1296138600000,
            "regularMarketChange": 0.62999725,
            "regularMarketTime": 1601409595,
            "regularMarketPrice": 96.25,
            "regularMarketDayHigh": 97.28,
            "regularMarketDayRange": "96.0848 - 97.28",
            "regularMarketDayLow": 96.0848,
            "regularMarketVolume": 19387,
            "regularMarketPreviousClose": 95.62,
            "bid": 95.29,
            "ask": 96.36,
            "bidSize": 9,
            "askSize": 12,
            "exchange": "PCX",
            "market": "us_market",
            "messageBoardId": "finmb_118789343",
            "fullExchangeName": "NYSEArca",
            "shortName": "SPDR S&P Health Care Equipment",
            "longName": "SPDR S&P Health Care Equipment ETF",
            "regularMarketOpen": 95.45,
            "averageDailyVolume3Month": 31826,
            "averageDailyVolume10Day": 24233,
            "fiftyTwoWeekLowChange": 38.02,
            "fiftyTwoWeekLowChangePercent": 0.65292805,
            "fiftyTwoWeekRange": "58.23 - 99.14",
            "fiftyTwoWeekHighChange": -2.8899994,
            "fiftyTwoWeekHighChangePercent": -0.02915069,
            "fiftyTwoWeekLow": 58.23,
            "fiftyTwoWeekHigh": 99.14,
            "ytdReturn": 4.06,
            "trailingThreeMonthReturns": 24.74,
            "trailingThreeMonthNavReturns": 24.37,
            "marketState": "PREPRE",
            "fiftyDayAverage": 95.218285,
            "fiftyDayAverageChange": 1.0317154,
            "fiftyDayAverageChangePercent": 0.010835266,
            "twoHundredDayAverage": 86.81486,
            "twoHundredDayAverageChange": 9.4351425,
            "twoHundredDayAverageChangePercent": 0.108681194,
            "sourceInterval": 15,
            "exchangeDataDelayedBy": 0,
            "exchangeTimezoneName": "America/New_York",
            "exchangeTimezoneShortName": "EDT",
            "gmtOffSetMilliseconds": -14400000,
            "esgPopulated": "false",
            "tradeable": "true",
            "symbol": "XHE",
        },
    ],
}

# Generator to parse by key
# Source: https://stackoverflow.com/questions/9807634/find-all-occurrences-of-a-key-in-nested-dictionaries-and-lists
def jsonGen(key, var):
    if hasattr(var, "items"):
        for k, v in var.items():
            if k == key:
                yield v
            if isinstance(v, dict):
                for result in jsonGen(key, v):
                    yield result
            elif isinstance(v, list):
                for d in v:
                    for result in jsonGen(key, d):
                        yield result

# define empty list
lst = []

for quote in dd["quotes"]:

    Company = list(jsonGen("shortName", quote))
    Ticker = list(jsonGen("symbol", quote))
    Asset = list(jsonGen("quoteType", quote))
    lst.append((Company[0], Ticker[0], Asset[0],))

# convert output to new array
array = np.asarray(lst)

# convert new array to dataframe
df = pd.DataFrame(array)


# define header
df.columns = ["Company", "Ticker", "Asset"]

# if file does exist...
if os.path.isfile("ETFs.csv"):

    df.to_csv("ETFs.csv", mode="a", header=False, index=False)
    
else:  # else create it

    df.to_csv("ETFs.csv", mode="w", header=True, index=False)